---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install required Python libraries
      pip:
        name:
          - botocore
          - boto3
        state: present

- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Postgres
      apt: name=postgresql state=present

    - name: Install Kubernetes
      apt: 
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      notify: Install Docker

  handlers:
    - name: Install Docker
      apt: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
